import type { User, Exercise, Roadmap, SkillProfile, RoadmapWeek } from './types';
export const MOCK_USERS: User[] = [
  { 
    id: 'u1', 
    name: 'Guitar God', 
    streak: 5,
    skillProfile: {
      alternatePicking: 75,
      sweepPicking: 40,
      legato: 80,
      tapping: 60,
      rhythm: 90,
      bending: 85,
      vibrato: 70,
      theory: 50
    }
  }
];
export const DEFAULT_SKILL_PROFILE: SkillProfile = {
  alternatePicking: 0,
  sweepPicking: 0,
  legato: 0,
  tapping: 0,
  rhythm: 0,
  bending: 0,
  vibrato: 0,
  theory: 0
};
export const SEED_EXERCISES: Exercise[] = [
  {
    id: 'ex1',
    title: 'Spider Walk',
    description: 'The classic chromatic finger independence exercise. Practice ascending and descending across all strings, moving up the neck one fret at a time.',
    difficulty: 'Beginner',
    technique: ['Finger Independence', 'Chromatic'],
    bpm: 80,
    category: 'Accuracy',
    moveable: true,
    defaultPosition: 1,
    // Pattern: 4 notes per string, ascending from low E to high E
    pattern: [
      // Low E string (6)
      [6, 0], [6, 1], [6, 2], [6, 3],
      // A string (5)
      [5, 0], [5, 1], [5, 2], [5, 3],
      // D string (4)
      [4, 0], [4, 1], [4, 2], [4, 3],
      // G string (3)
      [3, 0], [3, 1], [3, 2], [3, 3],
      // B string (2)
      [2, 0], [2, 1], [2, 2], [2, 3],
      // High E string (1)
      [1, 0], [1, 1], [1, 2], [1, 3],
    ],
    drill: {
      direction: 'alternate',
      startPosition: 1,
      endPosition: 12,
      positionIncrement: 1,
      repetitionsPerPosition: 1,
    },
  },
  {
    id: 'ex2',
    title: 'Minor Pentatonic Box 1',
    description: 'The most common pentatonic shape. Default position is A minor (5th fret). Move to different positions to play in different keys.',
    difficulty: 'Beginner',
    technique: ['Alternate Picking', 'Scales'],
    bpm: 100,
    category: 'Speed',
    moveable: true,
    defaultPosition: 5, // A minor
    // Pattern: Minor pentatonic box 1, ascending
    pattern: [
      // Low E string: root, b3
      [6, 0], [6, 3],
      // A string: 4, 5
      [5, 0], [5, 2],
      // D string: b7, root
      [4, 0], [4, 2],
      // G string: b3, 4
      [3, 0], [3, 2],
      // B string: 5, b7
      [2, 0], [2, 3],
      // High E string: root, b3
      [1, 0], [1, 3],
    ],
    drill: {
      direction: 'alternate',
      startPosition: 5,
      endPosition: 17, // Up to high A minor
      positionIncrement: 2, // Move in whole steps through common keys
    },
  },
  {
    id: 'ex3',
    title: 'Arpeggio Sequence',
    description: 'Three-note-per-string arpeggio pattern. Great for developing sweep picking or economy picking across strings.',
    difficulty: 'Advanced',
    technique: ['Sweep Picking', 'Arpeggios'],
    bpm: 120,
    category: 'Speed',
    moveable: true,
    defaultPosition: 12,
    // Pattern: Ascending arpeggio shape
    pattern: [
      // G string
      [3, 0], [3, 2], [3, 4],
      // B string
      [2, 0], [2, 1], [2, 3],
      // High E string
      [1, 0], [1, 1], [1, 4],
    ],
    drill: {
      direction: 'alternate',
      startPosition: 12,
      endPosition: 1,
      positionIncrement: -1, // Descend the neck
    },
  },
  {
    id: 'ex4',
    title: 'Economy Picking Threes',
    description: 'Three-note ascending pattern across strings. Focus on the pick direction change when crossing strings.',
    difficulty: 'Intermediate',
    technique: ['Economy Picking'],
    bpm: 100,
    category: 'Speed',
    moveable: true,
    defaultPosition: 5,
    pattern: [
      // Three notes ascending on G string
      [3, 0], [3, 2], [3, 4],
      // Continue on B string
      [2, 0], [2, 2], [2, 3],
      // Finish on high E
      [1, 0], [1, 2], [1, 3],
    ],
    drill: {
      direction: 'ascending',
      startPosition: 1,
      endPosition: 12,
      positionIncrement: 1,
    },
  },
  {
    id: 'ex5',
    title: 'Open Chord Transitions: G-C-D',
    description: 'Practice smooth transitions between the three most common open chords. Focus on minimizing finger movement and keeping time.',
    difficulty: 'Beginner',
    technique: ['Chord Changes', 'Rhythm'],
    bpm: 60,
    category: 'Accuracy',
    moveable: false,
    tablature: `e|--3-----0-----2-----|\nB|--0-----1-----3-----|\nG|--0-----0-----2-----|\nD|--0-----2-----0-----|\nA|--2-----3-----------|\nE|--3-----------------|`,
  },
];
const ALTERNATE_PICKING_WEEKS: RoadmapWeek[] = [
  {
    weekNumber: 1,
    title: 'Motion Audit',
    focus: 'Establish efficient picking motion, eliminate tension',
    theoryBite: 'The pick should move the minimum distance needed. Most speed is lost to excessive motion, not lack of muscle.',
    targetBpmRange: '60–70 BPM',
    milestone: 'Can play chromatic 1-2-3-4 at 70 BPM with zero tension, zero missed picks',
    exercises: [
      { name: 'Single String Chromatic', description: '1-2-3-4 on high E, strict alternate picking', targetBpm: '60 BPM', durationMinutes: 5, exerciseId: 'ex1' },
      { name: 'Tremolo Bursts', description: '4 notes as fast as possible, then rest. Focus on relaxation between bursts', durationMinutes: 5 },
      { name: 'Accent Patterns', description: '1-2-3-4 with accent on 1, then 2, etc. Forces pick control', targetBpm: '60 BPM', durationMinutes: 5 },
      { name: 'Metronome Locking', description: 'Single note, quarter notes, eyes closed. Lock in before moving on', targetBpm: '70 BPM', durationMinutes: 5 },
    ],
  },
  {
    weekNumber: 2,
    title: 'String Crossing Foundation',
    focus: 'Inside and outside picking across two strings',
    theoryBite: '"Inside picking" (pick trapped between strings) and "outside picking" (pick escapes over string) require different motions. Identify which is harder for you.',
    targetBpmRange: '70–80 BPM',
    milestone: 'Can identify your weaker picking direction, both feel equally controlled at 80 BPM',
    exercises: [
      { name: 'Two-String Loop', description: '5-7 on B, 5-7 on E, loop. Strict alternate', targetBpm: '70 BPM', durationMinutes: 6 },
      { name: 'Outside Picking Drill', description: 'Pattern that forces pick to escape outward', targetBpm: '70 BPM', durationMinutes: 6 },
      { name: 'Inside Picking Drill', description: 'Pattern that forces pick to stay between strings', targetBpm: '70 BPM', durationMinutes: 6 },
      { name: 'Combined Pattern', description: 'Mix of inside/outside in single phrase', targetBpm: '75 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 3,
    title: 'Three-String Patterns',
    focus: 'Scale fragments across three strings',
    theoryBite: 'Most metal riffs live in 2–3 string boxes. Master these positions and riffs become accessible.',
    targetBpmRange: '80–95 BPM',
    milestone: 'Clean three-string runs at 95 BPM, both directions',
    exercises: [
      { name: 'Three-Note-Per-String Fragment', description: 'E minor pattern, strings 1-2-3', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Descending Sequence', description: 'Same pattern descending, often harder', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Position Shift', description: 'Move the box up 2 frets mid-phrase', targetBpm: '85 BPM', durationMinutes: 6 },
      { name: 'ABR-Style Melodic Run', description: 'Simplified melodic run in ABR style', targetBpm: '90 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 4,
    title: 'Synchronization Focus',
    focus: 'Both hands perfectly together',
    theoryBite: 'At higher speeds, your pick and fret hands desync. This week forces them back together with accent exercises.',
    targetBpmRange: '95–110 BPM',
    milestone: 'Clean playing at 110 BPM with intentional accents',
    exercises: [
      { name: 'Accent Sync', description: 'Accent beat 1 of every 4, fret hand must match', targetBpm: '95 BPM', durationMinutes: 6 },
      { name: 'Gallop Patterns', description: 'Down-down-up rhythm, common in metal', targetBpm: '100 BPM', durationMinutes: 6 },
      { name: 'Pause and Resume', description: 'Play 8 notes, pause 4, resume. Tests control', targetBpm: '100 BPM', durationMinutes: 6 },
      { name: 'Speed Burst', description: '8 notes at 120, 8 at 100. Build burst capacity', targetBpm: '100–120', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 5,
    title: 'Speed Building',
    focus: 'Progressive overload',
    theoryBite: 'Your nervous system adapts to speed incrementally. Push 10% above comfort, then consolidate.',
    targetBpmRange: '110–140 BPM',
    milestone: 'Can burst to 140 BPM cleanly for 2–4 bars',
    exercises: [
      { name: 'Plateau Breaker', description: 'Play at max clean speed for 2 min, rest, push 5 BPM', targetBpm: '120 BPM', durationMinutes: 8 },
      { name: 'Sixteenth Note Runs', description: 'Full bar of 16ths on scale pattern', targetBpm: '120 BPM', durationMinutes: 6 },
      { name: 'Tempo Pyramid', description: '100→120→140→120→100. Build then recover', targetBpm: 'Variable', durationMinutes: 6 },
      { name: 'Riff Application', description: 'Apply to actual riff fragment', targetBpm: '130 BPM', durationMinutes: 5 },
    ],
  },
  {
    weekNumber: 6,
    title: 'Integration & Riffs',
    focus: 'Apply to real music',
    theoryBite: 'Technique serves music. This week connects exercises to actual riffs.',
    targetBpmRange: '140–160+ BPM',
    milestone: 'Can play a metal riff cleanly at 150+ BPM',
    exercises: [
      { name: 'Metal Riff #1', description: 'Simplified ABR-style riff (Composure intro style)', targetBpm: '140 BPM', durationMinutes: 8 },
      { name: 'Speed Consolidation', description: 'Chromatic exercise from Week 1, now at speed', targetBpm: '150 BPM', durationMinutes: 5, exerciseId: 'ex1' },
      { name: 'Endurance Run', description: '2-minute continuous playing at 140', targetBpm: '140 BPM', durationMinutes: 5 },
      { name: 'Push Day', description: 'Attempt 160+, note where it breaks down', targetBpm: '160 BPM', durationMinutes: 5 },
    ],
  },
];

const METALCORE_RHYTHM_WEEKS: RoadmapWeek[] = [
  {
    weekNumber: 1,
    title: 'Palm Mute Mechanics',
    focus: 'Consistent mute pressure, clean attack',
    theoryBite: 'Palm mute position changes the tone — closer to bridge = tighter, toward neck = looser. Find your sweet spot for metal tone.',
    targetBpmRange: '80–100 BPM',
    milestone: 'Consistent mute tone, no accidental open notes',
    exercises: [
      { name: 'Mute Pressure Drill', description: 'Same note, vary mute pressure from tight to loose', targetBpm: '80 BPM', durationMinutes: 5 },
      { name: 'Open-to-Mute Transitions', description: 'Alternate between open and muted on same string', targetBpm: '90 BPM', durationMinutes: 5 },
      { name: 'Single String Chugs', description: 'Continuous 8th notes, perfect consistency', targetBpm: '100 BPM', durationMinutes: 5 },
      { name: 'Power Chord Mutes', description: 'Palm muted power chords, E5-F5-G5', targetBpm: '90 BPM', durationMinutes: 5 },
    ],
  },
  {
    weekNumber: 2,
    title: 'Syncopation Basics',
    focus: 'Off-beat accents, the groove of metal',
    theoryBite: 'Metalcore rarely sits on straight beats. Syncopation = accenting the "and" of beats. This creates the bounce.',
    targetBpmRange: '90–110 BPM',
    milestone: 'Can feel and play syncopated rhythms without counting',
    exercises: [
      { name: 'Off-Beat Accents', description: 'Accent the "and" of each beat (1-AND-2-AND)', targetBpm: '90 BPM', durationMinutes: 6 },
      { name: 'Djent Pattern #1', description: '0-0-0-x-0-x-0-0 (x = rest)', targetBpm: '100 BPM', durationMinutes: 6 },
      { name: 'Tied Note Feel', description: 'Hold notes across beat boundaries', targetBpm: '100 BPM', durationMinutes: 6 },
      { name: 'Breakdown Groove', description: 'Simple breakdown pattern with syncopation', targetBpm: '110 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 3,
    title: 'Gallops and Rhythmic Variation',
    focus: 'Triplet feels, gallops, rhythmic vocabulary',
    theoryBite: 'The gallop (down-down-up) is a foundational metal rhythm. It\'s technically a dotted-eighth + sixteenth pattern.',
    targetBpmRange: '100–130 BPM',
    milestone: 'Smooth gallops at 130 BPM, can switch between rhythm types',
    exercises: [
      { name: 'Basic Gallop', description: 'D-D-U continuous on low E', targetBpm: '100 BPM', durationMinutes: 5 },
      { name: 'Reverse Gallop', description: 'U-D-D continuous', targetBpm: '100 BPM', durationMinutes: 5 },
      { name: 'Gallop with Chord Changes', description: 'Gallop while moving E5-A5-D5', targetBpm: '110 BPM', durationMinutes: 5 },
      { name: 'Mixed Rhythm', description: '8ths + gallop + 16ths in one phrase', targetBpm: '120 BPM', durationMinutes: 5 },
      { name: 'ABR Rhythm Study', description: 'Breakdown rhythm from Composure', targetBpm: '125 BPM', durationMinutes: 5 },
    ],
  },
  {
    weekNumber: 4,
    title: 'Breakdowns & Dynamics',
    focus: 'Half-time grooves, dynamic control, space',
    theoryBite: 'Breakdowns work because of contrast — they\'re half as fast but twice as heavy. The space between notes creates impact.',
    targetBpmRange: '70–90 BPM (half-time feel)',
    milestone: 'Can play a breakdown with confident, heavy attack',
    exercises: [
      { name: 'Half-Time Chugs', description: 'Heavy, spaced hits with room to breathe', targetBpm: '70 BPM', durationMinutes: 6 },
      { name: 'Dynamic Swells', description: 'Soft → loud on repeated phrase', targetBpm: '80 BPM', durationMinutes: 5 },
      { name: 'Rest Placement', description: 'Riff with intentional rests for impact', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Classic Breakdown', description: 'Archetypal metalcore breakdown pattern', targetBpm: '85 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 5,
    title: 'Full Song Application',
    focus: 'String together techniques into song structures',
    theoryBite: 'Metalcore songs typically follow: Intro → Verse → Chorus → Breakdown → Bridge → Chorus. Rhythm patterns shift with sections.',
    targetBpmRange: 'Variable',
    milestone: 'Can play through a song structure maintaining tightness',
    exercises: [
      { name: 'Verse Rhythm', description: 'Continuous driving rhythm, steady', targetBpm: '130 BPM', durationMinutes: 6 },
      { name: 'Chorus Chords', description: 'More open, sustained power chords', targetBpm: '130 BPM', durationMinutes: 5 },
      { name: 'Breakdown Transition', description: 'Go from verse speed to breakdown', targetBpm: 'Variable', durationMinutes: 6 },
      { name: 'Mini-Song Structure', description: 'Play through V-C-B-C structure', targetBpm: 'Variable', durationMinutes: 8 },
    ],
  },
];

const LEFT_HAND_WEEKS: RoadmapWeek[] = [
  {
    weekNumber: 1,
    title: 'Hammer-On Strength',
    focus: 'Strong, even hammer-ons from each finger',
    theoryBite: 'A good hammer-on should be as loud as a picked note. Most players\' 3rd and 4th fingers are weak — this week fixes that.',
    targetBpmRange: '60–80 BPM',
    milestone: 'Hammer-ons from all 4 fingers equally strong',
    exercises: [
      { name: 'Single Finger Hammers', description: 'Pick 5, hammer 7 with index. Repeat each finger', targetBpm: '60 BPM', durationMinutes: 6 },
      { name: 'Finger 3–4 Focus', description: 'Isolated hammer-ons with ring and pinky', targetBpm: '60 BPM', durationMinutes: 6 },
      { name: 'Hammer Flurries', description: 'Pick once, hammer 3 notes (5-6-7-8)', targetBpm: '70 BPM', durationMinutes: 6 },
      { name: 'Volume Matching', description: 'Hammer as loud as picked note, check with ear', targetBpm: '70 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 2,
    title: 'Pull-Off Control',
    focus: 'Clean pull-offs without buzzing',
    theoryBite: 'Pull-offs aren\'t just lifting — you\'re plucking the string with your fretting finger. Pull slightly downward as you release.',
    targetBpmRange: '60–80 BPM',
    milestone: 'Clean pull-offs, can trill smoothly at 80 BPM',
    exercises: [
      { name: 'Pull-Off Basics', description: '7 to 5, each finger combination', targetBpm: '60 BPM', durationMinutes: 6 },
      { name: 'No-Buzz Pulls', description: 'Focus on clean release, no fret buzz', targetBpm: '60 BPM', durationMinutes: 6 },
      { name: 'Trills', description: 'Rapid hammer-pull on single fret pair', targetBpm: '70 BPM', durationMinutes: 6 },
      { name: 'Descending Legato', description: '8-7-5 all legato, one pick', targetBpm: '70 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 3,
    title: 'Combined Legato Phrases',
    focus: 'Flowing legato lines',
    theoryBite: 'Great legato playing sounds like a saxophone — no gaps, smooth sustain from note to note. Think "connect" not "hit."',
    targetBpmRange: '80–100 BPM',
    milestone: 'Can play 3-string legato phrase smoothly at 100 BPM',
    exercises: [
      { name: '4-Note Legato Cell', description: '5-7-8-7 continuous, one pick per 4 notes', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'String Crossing Legato', description: 'Legato phrase across 2 strings', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Legato Scale Run', description: 'Full scale position with minimal picking', targetBpm: '90 BPM', durationMinutes: 6 },
      { name: 'Speed Push', description: 'Same phrase, push BPM until it breaks', targetBpm: '100 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 4,
    title: 'Stretching Foundations',
    focus: 'Gradually expand fret reach',
    theoryBite: 'Stretch tolerance is built slowly. Never stretch to pain — discomfort is fine, pain means stop. Position your thumb lower on the neck back for bigger stretches.',
    targetBpmRange: 'Slow (form focus)',
    milestone: 'Comfortable 4-fret stretch at 12th fret, working toward 7th fret',
    exercises: [
      { name: '3-Fret Stretch', description: '1-3-5 pattern, moving up neck where easier', targetBpm: 'Slow', durationMinutes: 6 },
      { name: '4-Fret Stretch', description: '1-2-4-5 pattern, start high on neck', targetBpm: 'Slow', durationMinutes: 6 },
      { name: 'Stretch + Legato', description: 'Combine stretch with hammer-on', targetBpm: 'Slow', durationMinutes: 6 },
      { name: 'Position Shift', description: 'Stretch in multiple neck positions', targetBpm: 'Slow', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 5,
    title: 'Applied Legato Licks',
    focus: 'Musical application',
    theoryBite: 'Legato works beautifully for melodic metal leads — think of the smooth runs in bands like Intervals or Polyphia.',
    targetBpmRange: '90–120 BPM',
    milestone: 'Can play a legato solo section musically',
    exercises: [
      { name: 'Metal Legato Lick #1', description: 'Joe Satriani-style smooth run', targetBpm: '90 BPM', durationMinutes: 7 },
      { name: 'Pentatonic Legato', description: 'Minor pentatonic with legato only', targetBpm: '100 BPM', durationMinutes: 7, exerciseId: 'ex2' },
      { name: 'Math Rock Legato', description: 'Tapping-prep phrase with stretches', targetBpm: '100 BPM', durationMinutes: 6 },
      { name: 'Full Application', description: 'Solo passage using all techniques', targetBpm: '110 BPM', durationMinutes: 5 },
    ],
  },
];

const SWEEP_PICKING_WEEKS: RoadmapWeek[] = [
  {
    weekNumber: 1,
    title: 'The Sweep Motion',
    focus: 'Understand what a sweep actually is',
    theoryBite: 'Sweeping isn\'t fast strumming — it\'s a controlled "fall" of the pick across strings, each note ringing separately. Think of it like a very slow strum where you mute each note as you leave it.',
    targetBpmRange: '40–50 BPM',
    milestone: 'Understand the motion, no "strummed" sound',
    exercises: [
      { name: 'Two-String Rake', description: 'Just 2 notes, one pick motion down', targetBpm: '40 BPM', durationMinutes: 6 },
      { name: 'Roll Finger Practice', description: 'Barre one finger, roll to mute previous note', targetBpm: '40 BPM', durationMinutes: 6 },
      { name: 'Down Sweep Only', description: '3 notes descending, one pick motion', targetBpm: '50 BPM', durationMinutes: 6 },
      { name: 'Up Sweep Only', description: '3 notes ascending, one pick motion', targetBpm: '50 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 2,
    title: 'Three-String Arpeggios',
    focus: 'Minor and major triads, 3 strings',
    theoryBite: 'A minor triad = root, minor 3rd, 5th. These shapes repeat all over the neck. Learn one shape, know them all.',
    targetBpmRange: '50–70 BPM',
    milestone: 'Clean 3-string sweep at 70 BPM, both directions',
    exercises: [
      { name: 'Am Triad (3 string)', description: 'A-C-E on strings 3-2-1', targetBpm: '50 BPM', durationMinutes: 6 },
      { name: 'A Major Triad', description: 'A-C#-E on strings 3-2-1', targetBpm: '50 BPM', durationMinutes: 6 },
      { name: 'Ascending + Descending', description: 'Down sweep + up sweep connected', targetBpm: '60 BPM', durationMinutes: 6, exerciseId: 'ex3' },
      { name: 'Moving Triads', description: 'Am → Dm → Em with sweeps', targetBpm: '60 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 3,
    title: 'Adding the 4th String',
    focus: 'Expand to 4-string shapes',
    theoryBite: '4-string sweeps often add the octave on top. This makes a fuller arpeggio sound — root, 3rd, 5th, octave.',
    targetBpmRange: '60–80 BPM',
    milestone: 'Clean 4-string sweeps at 80 BPM',
    exercises: [
      { name: '4-String Minor', description: 'Am shape across 4 strings', targetBpm: '60 BPM', durationMinutes: 7 },
      { name: '4-String Major', description: 'A major shape across 4 strings', targetBpm: '60 BPM', durationMinutes: 7 },
      { name: 'Position Shifts', description: 'Move shapes up the neck', targetBpm: '70 BPM', durationMinutes: 5 },
      { name: 'Timing Focus', description: 'With metronome, nail the rhythm', targetBpm: '75 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 4,
    title: 'Five-String Sweep Shapes',
    focus: 'Full arpeggio shapes',
    theoryBite: '5-string sweeps are the "classic" metal sweep. Shape looks like a diagonal line across the neck. These shapes come from CAGED chord forms.',
    targetBpmRange: '60–80 BPM',
    milestone: 'Can loop 5-string sweep continuously at 80 BPM',
    exercises: [
      { name: '5-String Minor Shape', description: 'Full Am arpeggio', targetBpm: '60 BPM', durationMinutes: 8 },
      { name: '5-String Major Shape', description: 'Full A major arpeggio', targetBpm: '60 BPM', durationMinutes: 8 },
      { name: 'Descending Focus', description: 'Many players struggle going back up', targetBpm: '70 BPM', durationMinutes: 5 },
      { name: 'Continuous Loop', description: 'Up and down without stopping', targetBpm: '70 BPM', durationMinutes: 4 },
    ],
  },
  {
    weekNumber: 5,
    title: 'Speed & Cleanliness',
    focus: 'Push tempo while maintaining separation',
    theoryBite: 'Speed comes from efficiency. If your sweep is clean at 80, it should work at 100 — you\'re just moving faster, not differently.',
    targetBpmRange: '80–110 BPM',
    milestone: 'Clean 5-string sweep at 110 BPM',
    exercises: [
      { name: 'Tempo Push (5-string)', description: 'Gradually increase from 80 to 100', targetBpm: '100 BPM', durationMinutes: 8 },
      { name: 'Problem Spot Isolation', description: 'Find the note that\'s sloppy, drill it', targetBpm: 'Variable', durationMinutes: 6 },
      { name: 'Sweep + Tap', description: 'Add tapped note at top (optional)', targetBpm: '90 BPM', durationMinutes: 6 },
      { name: 'Arpeggio Sequence', description: 'Am → Em → Dm sweep sequence', targetBpm: '100 BPM', durationMinutes: 5 },
    ],
  },
  {
    weekNumber: 6,
    title: 'Musical Application',
    focus: 'Sweeps in musical context',
    theoryBite: 'Sweeps sound best when they outline chord changes. Follow the song\'s chords with matching arpeggios.',
    targetBpmRange: '100–130 BPM',
    milestone: 'Can incorporate sweeps into a solo naturally',
    exercises: [
      { name: 'Chord Progression Sweeps', description: 'Sweep arpeggios over Am-F-C-G', targetBpm: '100 BPM', durationMinutes: 7 },
      { name: 'Metal Solo Phrase', description: 'Sweep into scale run', targetBpm: '110 BPM', durationMinutes: 7 },
      { name: 'Economy Hybrid', description: 'Mix sweeps with alternate picking', targetBpm: '110 BPM', durationMinutes: 6, exerciseId: 'ex4' },
      { name: 'Full Application', description: '8-bar solo using sweeps', targetBpm: '120 BPM', durationMinutes: 5 },
    ],
  },
];

const TAPPING_WEEKS: RoadmapWeek[] = [
  {
    weekNumber: 1,
    title: 'Tapping Mechanics',
    focus: 'Clean tap attack, controlled pull-off',
    theoryBite: 'The tap is a hammer-on with your picking hand. The key is the pull-off after — you need to pull off to the next note, not just lift.',
    targetBpmRange: '60–80 BPM',
    milestone: 'Even volume between tapped and fretted notes',
    exercises: [
      { name: 'Single Tap', description: 'Fret 5, tap 12, pull-off to 5', targetBpm: '60 BPM', durationMinutes: 6 },
      { name: 'Tap Volume', description: 'Match tap volume to fretted notes', targetBpm: '60 BPM', durationMinutes: 6 },
      { name: 'Tap-Pull-Hammer', description: '12t-5p-8h pattern continuous', targetBpm: '70 BPM', durationMinutes: 6 },
      { name: 'Different Tap Fingers', description: 'Try tapping with middle finger too', targetBpm: '70 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 2,
    title: 'Single-String Patterns',
    focus: 'Extended tapping phrases on one string',
    theoryBite: 'Single-string tapping can outline arpeggios or create wide interval leaps impossible with fretting hand alone.',
    targetBpmRange: '80–100 BPM',
    milestone: 'Fluid single-string tapping at 100 BPM',
    exercises: [
      { name: 'Arpeggio Tap', description: '5-8-12 (Am arpeggio)', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Ascending Pattern', description: '5-8-12-8-5-8-12…', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Moving Tap Point', description: 'Keep fret hand, move tap: 12, 13, 14', targetBpm: '90 BPM', durationMinutes: 6 },
      { name: 'Speed Push', description: 'Take pattern to 100+', targetBpm: '100 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 3,
    title: 'Multi-String Tapping',
    focus: 'Tapping across strings',
    theoryBite: 'Multi-string tapping is how you get those "piano-like" passages. Each string can have its own tapped note.',
    targetBpmRange: '70–90 BPM',
    milestone: 'Clean 3-string tapped phrase',
    exercises: [
      { name: 'Two-String Tap', description: 'Tap pattern on E, then B string', targetBpm: '70 BPM', durationMinutes: 7 },
      { name: 'String Crossing', description: 'Tap E-12, then B-12', targetBpm: '75 BPM', durationMinutes: 6 },
      { name: 'Basic Tapped Arpeggio', description: 'Three strings, Am shape tapped', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Coordination Drill', description: 'Alternating tap positions per string', targetBpm: '85 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 4,
    title: 'Math Rock Tapping Patterns',
    focus: 'Style-specific application',
    theoryBite: 'Math rock tapping often uses open strings and unconventional intervals. The clash creates that distinctive "bright" sound.',
    targetBpmRange: '80–110 BPM',
    milestone: 'Can play a recognizable math rock tapping phrase',
    exercises: [
      { name: 'Open String Tap', description: 'Tap while open strings ring', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Intervals Tap', description: 'Tap 4ths and 5ths, not just octaves', targetBpm: '90 BPM', durationMinutes: 6 },
      { name: 'Polyrhythmic Tap', description: '3-against-2 tapping feel', targetBpm: '90 BPM', durationMinutes: 7 },
      { name: 'TTNG-Style Pattern', description: 'Simplified math rock tapping phrase', targetBpm: '100 BPM', durationMinutes: 6 },
    ],
  },
  {
    weekNumber: 5,
    title: 'Full Integration',
    focus: 'Combining with other techniques',
    theoryBite: 'The best tappers transition seamlessly between tapping and regular playing. Practice the transitions, not just the tapping.',
    targetBpmRange: '100–130 BPM',
    milestone: 'Tapping feels like a natural part of your vocabulary',
    exercises: [
      { name: 'Tap → Regular Transition', description: 'Smooth switch mid-phrase', targetBpm: '100 BPM', durationMinutes: 6 },
      { name: 'Sweep → Tap', description: 'Classic metal combo', targetBpm: '100 BPM', durationMinutes: 7 },
      { name: 'Full Tapping Solo', description: '16-bar piece using all techniques', targetBpm: '110 BPM', durationMinutes: 7 },
      { name: 'Improvised Tapping', description: 'Jam over backing track using taps', targetBpm: 'Variable', durationMinutes: 5 },
    ],
  },
];

const LEAD_GUITAR_WEEKS: RoadmapWeek[] = [
  {
    weekNumber: 1,
    title: 'The Minor Pentatonic (Your Home Base)',
    focus: 'One scale shape, musical application',
    theoryBite: 'The minor pentatonic (1-b3-4-5-b7) is your "safe zone" for rock/metal. Every note works over a minor chord or power chord progression. Learn one shape perfectly before learning more.',
    targetBpmRange: '80–90 BPM',
    milestone: 'Can improvise basic phrases over a backing track',
    theoryHomework: 'Name every note in Am pentatonic (A, C, D, E, G)',
    exercises: [
      { name: 'Shape 1 (Am)', description: 'Box 1 at 5th fret, ascending/descending', targetBpm: '80 BPM', durationMinutes: 5, exerciseId: 'ex2' },
      { name: 'Note Targeting', description: 'Find the root (A) in the shape, emphasize it', targetBpm: 'Slow', durationMinutes: 5 },
      { name: 'Simple Lick', description: '2–3 note phrase using the scale', targetBpm: '90 BPM', durationMinutes: 5 },
      { name: 'Jam Application', description: 'Play over Am backing track, stay in box', targetBpm: 'Variable', durationMinutes: 10 },
    ],
  },
  {
    weekNumber: 2,
    title: 'Bending & Vibrato (The Feel)',
    focus: 'Expressive techniques',
    theoryBite: 'Bending and vibrato are what separate robotic playing from emotional playing. A bent note should land exactly on pitch — usually a half-step or whole-step up.',
    targetBpmRange: 'Slow (technique focus)',
    milestone: 'Bends land on pitch, vibrato is controlled',
    exercises: [
      { name: 'Half-Step Bend', description: 'Bend 7th fret G to match 8th fret pitch', targetBpm: 'Slow', durationMinutes: 5 },
      { name: 'Whole-Step Bend', description: 'Bend 7th fret G to match 9th fret pitch', targetBpm: 'Slow', durationMinutes: 5 },
      { name: 'Vibrato Control', description: 'Wide vs. narrow, slow vs. fast', targetBpm: 'Slow', durationMinutes: 5 },
      { name: 'Bend + Vibrato Combo', description: 'Bend up, add vibrato at top', targetBpm: 'Slow', durationMinutes: 5 },
      { name: 'Musical Application', description: 'Simple lick with bends', targetBpm: '80 BPM', durationMinutes: 5 },
    ],
  },
  {
    weekNumber: 3,
    title: 'Connecting Positions',
    focus: 'Breaking out of "the box"',
    theoryBite: 'The pentatonic has 5 positions that connect across the neck. Learning to shift positions lets you follow the music up and down the neck.',
    targetBpmRange: '80–90 BPM',
    milestone: 'Can move between 2 positions smoothly',
    theoryHomework: 'Map pentatonic positions 1 and 2, find where they overlap',
    exercises: [
      { name: 'Position 1 → 2 Shift', description: 'Connect two adjacent shapes', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Slide Connections', description: 'Use slides to move between positions', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Full Neck Run', description: 'Pentatonic from fret 5 to fret 17', targetBpm: '90 BPM', durationMinutes: 6 },
      { name: 'Backing Track Work', description: 'Improvise using 2 positions', targetBpm: 'Variable', durationMinutes: 7 },
    ],
  },
  {
    weekNumber: 4,
    title: 'The Natural Minor Scale (More Notes)',
    focus: 'Adding two notes to pentatonic',
    theoryBite: 'Natural minor = pentatonic + 2 notes (2 and b6). These extra notes add color but can sound "wrong" if you land on them too hard. Use them as passing tones.',
    targetBpmRange: '80–100 BPM',
    milestone: 'Can use natural minor without clashing',
    theoryHomework: 'Identify which notes are "safe" (pent) vs. "color" (2, b6)',
    exercises: [
      { name: 'Am Natural Minor', description: '3-note-per-string shape', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Compare to Pentatonic', description: 'Play both, hear the difference', targetBpm: '80 BPM', durationMinutes: 5 },
      { name: 'Passing Tone Practice', description: 'Use 2 and b6 as passing notes only', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Full Scale Sequence', description: '3-note sequences up the scale', targetBpm: '100 BPM', durationMinutes: 5 },
    ],
  },
  {
    weekNumber: 5,
    title: 'Chord Tone Soloing',
    focus: 'Following the chord changes',
    theoryBite: 'Great solos follow the chords. Over Am, emphasize A-C-E. Over G, emphasize G-B-D. This is called "chord tone soloing."',
    targetBpmRange: 'Variable',
    milestone: 'Your solo sounds like it "follows" the progression',
    theoryHomework: 'Write out chord tones for Am, G, F, E',
    exercises: [
      { name: 'Find Chord Tones', description: 'In your scale shape, identify Am, G, F, E notes', targetBpm: 'Slow', durationMinutes: 7 },
      { name: 'Am → G Change', description: 'Land on A over Am, land on G over G chord', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Progression Solo', description: 'Solo over Am-G-F-E, follow each chord', targetBpm: 'Variable', durationMinutes: 7 },
      { name: 'Target Note Practice', description: 'Pick target note before playing', targetBpm: 'Variable', durationMinutes: 5 },
    ],
  },
  {
    weekNumber: 6,
    title: 'Building Full Solos',
    focus: 'Structure and phrasing',
    theoryBite: 'A good solo tells a story — intro, build-up, climax, resolution. Start simple, build tension, hit a peak, then resolve.',
    targetBpmRange: 'Variable',
    milestone: 'Can play a structured, musical solo over a progression',
    exercises: [
      { name: 'Call & Response', description: 'Play a phrase, "answer" it', targetBpm: 'Variable', durationMinutes: 5 },
      { name: 'Dynamic Arc', description: 'Start quiet, build to peak', targetBpm: 'Variable', durationMinutes: 5 },
      { name: 'Space & Silence', description: 'Leave gaps, let notes breathe', targetBpm: 'Variable', durationMinutes: 5 },
      { name: 'Full 16-Bar Solo', description: 'Compose and play a complete solo', targetBpm: 'Variable', durationMinutes: 10 },
    ],
  },
];

const RHYTHM_TIMING_WEEKS: RoadmapWeek[] = [
  {
    weekNumber: 1,
    title: 'Quarter Note Lock',
    focus: 'Basic metronome alignment',
    theoryBite: 'Before subdividing, you need to internalize the quarter note. This is harder than it sounds — most players rush or drag.',
    targetBpmRange: '60–90 BPM',
    milestone: 'Can lock with metronome for 2 minutes without drifting',
    exercises: [
      { name: 'Quarter Note Strums', description: 'One strum per click, perfect alignment', targetBpm: '60 BPM', durationMinutes: 5 },
      { name: 'Beat 1 Only', description: 'Only play on beat 1 of each bar', targetBpm: '70 BPM', durationMinutes: 5 },
      { name: 'Gap Metronome', description: 'Metronome on 1 and 3, you play 2 and 4', targetBpm: '80 BPM', durationMinutes: 5 },
      { name: 'Silent Beats', description: 'Play 3 beats, silent on 4, check alignment', targetBpm: '80 BPM', durationMinutes: 5 },
      { name: 'Eyes Closed', description: 'Maintain timing without visual', targetBpm: '80 BPM', durationMinutes: 5 },
    ],
  },
  {
    weekNumber: 2,
    title: 'Eighth Notes & Counting',
    focus: '1-and-2-and feel',
    theoryBite: 'Eighth notes = 2 notes per beat. The "ands" are equally important to the downbeats. Count out loud: "1-and-2-and-3-and-4-and"',
    targetBpmRange: '80–90 BPM',
    milestone: 'Can feel the "and" without thinking',
    exercises: [
      { name: 'Eighth Note Strums', description: 'Two per click, all downstrokes', targetBpm: '80 BPM', durationMinutes: 5 },
      { name: 'Alternate Picking 8ths', description: 'Down-up per beat', targetBpm: '90 BPM', durationMinutes: 5 },
      { name: 'Accent Downbeats', description: '8ths but louder on 1,2,3,4', targetBpm: '90 BPM', durationMinutes: 5 },
      { name: 'Accent Upbeats', description: '8ths but louder on "ands"', targetBpm: '90 BPM', durationMinutes: 5 },
      { name: 'Count + Play', description: 'Say "1-and-2-and" while playing', targetBpm: '80 BPM', durationMinutes: 5 },
    ],
  },
  {
    weekNumber: 3,
    title: 'Sixteenth Notes',
    focus: '1-e-and-a subdivisions',
    theoryBite: 'Sixteenths = 4 notes per beat. Count: "1-e-and-a-2-e-and-a". This is the foundation for fast metal rhythms.',
    targetBpmRange: '70–80 BPM',
    milestone: 'Can switch between 8ths and 16ths cleanly',
    exercises: [
      { name: 'Straight 16ths', description: '4 notes per click', targetBpm: '70 BPM', durationMinutes: 5 },
      { name: '16th Rest Patterns', description: '1-e-a (missing "and")', targetBpm: '70 BPM', durationMinutes: 6 },
      { name: 'Mixed 8th/16th', description: '8ths → 16ths → 8ths', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Metal Gallop', description: '1-e-and (missing "a")', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Count + Play', description: 'Vocalize subdivisions', targetBpm: '80 BPM', durationMinutes: 5 },
    ],
  },
  {
    weekNumber: 4,
    title: 'Application & Odd Feels',
    focus: 'Real-world timing challenges',
    theoryBite: 'Many metal/math rock songs use triplets (3 notes per beat) or odd groupings. This week introduces triplet feel.',
    targetBpmRange: '70–90 BPM',
    milestone: 'Timing feels automatic, not forced',
    exercises: [
      { name: 'Triplet Feel', description: '3 notes per beat, even spacing', targetBpm: '70 BPM', durationMinutes: 6 },
      { name: 'Triplet vs 16th', description: 'Switch between feels', targetBpm: '80 BPM', durationMinutes: 6 },
      { name: 'Groove Pattern', description: 'Real riff with mixed subdivisions', targetBpm: '90 BPM', durationMinutes: 6 },
      { name: 'Backing Track Work', description: 'Play rhythm over drums, lock in', targetBpm: 'Variable', durationMinutes: 7 },
    ],
  },
];

export const SEED_ROADMAPS: Roadmap[] = [
  {
    id: 'road1',
    title: 'Alternate Picking Precision',
    description: 'Build clean, consistent alternate picking up to 160+ BPM through progressive technique work.',
    approach: 'Most players hit a speed wall because they never built clean mechanics at slow tempos. This roadmap enforces "slow is smooth, smooth is fast" — we\'ll spend weeks at uncomfortable slow tempos to rewire your picking motion, then speed will come naturally.',
    durationWeeks: 6,
    targetTechniques: ['alternate_picking', 'pick_accuracy', 'synchronization'],
    difficulty: 'Intermediate',
    timePerSessionMinutes: 25,
    prerequisites: ['road7'],
    theoryFocus: false,
    weeks: ALTERNATE_PICKING_WEEKS,
  },
  {
    id: 'road2',
    title: 'Metalcore Rhythm Foundations',
    description: 'Develop tight, percussive rhythm playing for metalcore — palm muting, syncopation, gallops, and breakdowns.',
    approach: 'Metalcore rhythm guitar is about precision, not just heaviness. Clean palm muting, locked-in timing, and dynamic control separate amateur chugging from pro-level tightness. We\'ll build this systematically.',
    durationWeeks: 5,
    targetTechniques: ['palm_muting', 'rhythm', 'syncopation', 'chugging'],
    difficulty: 'Beginner',
    timePerSessionMinutes: 25,
    prerequisites: ['road7'],
    theoryFocus: false,
    weeks: METALCORE_RHYTHM_WEEKS,
  },
  {
    id: 'road3',
    title: 'Left Hand Liberation',
    description: 'Develop fluid legato playing and comfortable 4–5 fret stretches through hammer-ons, pull-offs, and finger independence.',
    approach: 'Your fretting hand is probably undertrained compared to your picking hand. Legato forces the left hand to do the work, building strength and independence. Stretches expand your physical range on the neck.',
    durationWeeks: 5,
    targetTechniques: ['legato', 'hammer_ons', 'pull_offs', 'finger_independence', 'stretching'],
    difficulty: 'Intermediate',
    timePerSessionMinutes: 25,
    theoryFocus: false,
    weeks: LEFT_HAND_WEEKS,
  },
  {
    id: 'road4',
    title: 'Sweep Picking Foundations',
    description: 'Master clean 3-string and 5-string sweep arpeggios from the ground up.',
    approach: 'Sweep picking fails when players try to go fast before the motion is correct. We\'ll spend 3 weeks on the motion with just 2–3 strings before adding more strings. Patience here pays off massively.',
    durationWeeks: 6,
    targetTechniques: ['sweep_picking', 'arpeggios', 'economy_picking'],
    difficulty: 'Advanced',
    timePerSessionMinutes: 25,
    prerequisites: ['road1', 'road3'],
    theoryFocus: false,
    weeks: SWEEP_PICKING_WEEKS,
  },
  {
    id: 'road5',
    title: 'Two-Hand Tapping',
    description: 'Develop clean single-string and multi-string tapping technique, from basic mechanics to musical application.',
    approach: 'Tapping is an extension of legato — if your hammer-ons and pull-offs are weak, tapping will sound bad. We\'ll reinforce legato basics, then add the tapping hand progressively.',
    durationWeeks: 5,
    targetTechniques: ['tapping', 'legato', 'finger_independence'],
    difficulty: 'Advanced',
    timePerSessionMinutes: 25,
    prerequisites: ['road3'],
    theoryFocus: false,
    weeks: TAPPING_WEEKS,
  },
  {
    id: 'road6',
    title: 'Lead Guitar Foundations',
    description: 'Understand lead guitar fundamentals — scales, phrasing, bending, vibrato, and music theory for solos.',
    approach: 'This roadmap is different — it\'s 50% theory, 50% technique. You\'ll learn why certain notes work over certain chords, then apply that to create actual solos.',
    durationWeeks: 6,
    targetTechniques: ['scales', 'phrasing', 'bending', 'vibrato', 'theory'],
    difficulty: 'Intermediate',
    timePerSessionMinutes: 25,
    theoryFocus: true,
    weeks: LEAD_GUITAR_WEEKS,
  },
  {
    id: 'road7',
    title: 'Rhythm & Timing Fundamentals',
    description: 'Build rock-solid timing and subdivision mastery — the foundation that makes everything else work.',
    approach: 'This is the most underrated skill. Players obsess over speed but can\'t lock with a drummer. This roadmap builds internal clock and subdivision awareness.',
    durationWeeks: 4,
    targetTechniques: ['rhythm', 'timing', 'metronome_practice', 'subdivisions'],
    difficulty: 'Beginner',
    timePerSessionMinutes: 20,
    theoryFocus: false,
    weeks: RHYTHM_TIMING_WEEKS,
  },
];